-- MySQL Script generated by MySQL Workbench
-- Fri Sep  6 00:40:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema veterinario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema veterinario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `veterinario` DEFAULT CHARACTER SET utf8 ;
USE `veterinario` ;

-- -----------------------------------------------------
-- Table `veterinario`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinario`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `veterinario`.`medico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `crm` int not null,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinario`.`pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinario`.`pets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `imagem` VARCHAR(200) NOT NULL,
  `sintomas` VARCHAR(200) NOT NULL,
  `dono` VARCHAR(50) NOT NULL,
  `estado` INT NOT NULL,
  `medico` VARCHAR(50),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;





SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
